"""
Fixed question bank for the MSc Computer Science skill scorer.
10 topics x 10 questions each = 100 fixed questions.
Each question: {"q": str, "options": [4 strings], "answer": index of correct option}
Order of questions AND order of options are randomized per student session
(see app.py -> build_quiz_session), but the underlying bank itself is fixed.
"""

TOPICS = [
    "Python",
    "Java",
    "App Development",
    "Web Development",
    "Full Stack Development",
    "Git and GitHub",
    "AI Tools",
    "Cloud Computing",
    "Data Analyst",
    "IoT",
]

QUESTIONS = {
    "Python": [
        {"q": "Which keyword is used to define a function in Python?", "options": ["func", "def", "function", "lambda"], "answer": 1},
        {"q": "What is the output type of the range() function?", "options": ["list", "tuple", "range object", "generator"], "answer": 2},
        {"q": "Which data type is immutable in Python?", "options": ["list", "dict", "set", "tuple"], "answer": 3},
        {"q": "Which module is used for regular expressions in Python?", "options": ["regex", "re", "pyregex", "restr"], "answer": 1},
        {"q": "What does PEP 8 refer to?", "options": ["A Python package manager", "Python's style guide", "A testing framework", "A web framework"], "answer": 1},
        {"q": "Which of these is used to handle exceptions?", "options": ["try/except", "catch/throw", "if/else", "on/error"], "answer": 0},
        {"q": "What does the 'self' keyword represent in a class method?", "options": ["The class itself", "The instance of the class", "A static variable", "The parent class"], "answer": 1},
        {"q": "Which function converts a string to an integer?", "options": ["str()", "int()", "float()", "chr()"], "answer": 1},
        {"q": "Which library is commonly used for numerical computing in Python?", "options": ["NumPy", "React", "Bootstrap", "Django"], "answer": 0},
        {"q": "What is the correct file extension for Python files?", "options": [".pt", ".python", ".py", ".pyt"], "answer": 2},
    ],
    "Java": [
        {"q": "Java programs are compiled into which form?", "options": ["Machine code", "Bytecode", "Assembly", "Source map"], "answer": 1},
        {"q": "Which keyword is used to create a subclass in Java?", "options": ["implements", "extends", "inherits", "super"], "answer": 1},
        {"q": "Which of these is NOT a Java primitive type?", "options": ["int", "boolean", "String", "char"], "answer": 2},
        {"q": "What is the entry point method of a Java application?", "options": ["start()", "run()", "main()", "init()"], "answer": 2},
        {"q": "Which keyword prevents a class from being inherited?", "options": ["static", "final", "private", "constant"], "answer": 1},
        {"q": "What does JVM stand for?", "options": ["Java Virtual Machine", "Java Variable Method", "Java Verified Module", "Joint Virtual Machine"], "answer": 0},
        {"q": "Which collection type does not allow duplicate elements?", "options": ["List", "Set", "Map", "Queue"], "answer": 1},
        {"q": "Which keyword is used to handle exceptions in Java?", "options": ["try/catch", "try/except", "handle/error", "on/fail"], "answer": 0},
        {"q": "Which access modifier makes a member visible only within its class?", "options": ["public", "protected", "private", "default"], "answer": 2},
        {"q": "What is used to create an object in Java?", "options": ["make", "new", "create", "build"], "answer": 1},
    ],
    "App Development": [
        {"q": "Which language is primarily used for native Android development?", "options": ["Swift", "Kotlin", "Objective-C", "Dart"], "answer": 1},
        {"q": "Which language is used for native iOS development?", "options": ["Swift", "Java", "Kotlin", "C#"], "answer": 0},
        {"q": "What is Flutter mainly used for?", "options": ["Backend APIs", "Cross-platform mobile apps", "Database management", "Cloud hosting"], "answer": 1},
        {"q": "Which file format is used to package an Android app?", "options": [".exe", ".apk", ".app", ".dmg"], "answer": 1},
        {"q": "What does UI stand for in app development?", "options": ["User Interface", "Unified Instance", "Universal Index", "User Instruction"], "answer": 0},
        {"q": "Which tool is commonly used as an IDE for Android apps?", "options": ["Xcode", "Android Studio", "Eclipse", "NetBeans"], "answer": 1},
        {"q": "Which architecture pattern separates UI, logic, and data in apps?", "options": ["MVC", "CSV", "DNS", "SSH"], "answer": 0},
        {"q": "What is used to store data locally on mobile devices?", "options": ["SQLite", "Apache Server", "Nginx", "FTP"], "answer": 0},
        {"q": "Which of these is a cross-platform app framework?", "options": ["React Native", "Django", "Laravel", "Spring"], "answer": 0},
        {"q": "What does an emulator do in app development?", "options": ["Compiles code", "Simulates a device to run/test apps", "Manages databases", "Hosts servers"], "answer": 1},
    ],
    "Web Development": [
        {"q": "Which language is used to structure content on the web?", "options": ["CSS", "HTML", "JavaScript", "SQL"], "answer": 1},
        {"q": "Which language is used to style web pages?", "options": ["HTML", "CSS", "PHP", "JSON"], "answer": 1},
        {"q": "Which language adds interactivity to web pages?", "options": ["HTML", "CSS", "JavaScript", "XML"], "answer": 2},
        {"q": "What does HTTP stand for?", "options": ["HyperText Transfer Protocol", "High Transfer Text Protocol", "Hyperlink Text Transport Process", "Home Tool Transfer Protocol"], "answer": 0},
        {"q": "Which tag is used to create a hyperlink in HTML?", "options": ["<link>", "<a>", "<href>", "<url>"], "answer": 1},
        {"q": "What is the purpose of a CSS flexbox?", "options": ["Database queries", "Flexible layout arrangement", "Form validation", "Server routing"], "answer": 1},
        {"q": "Which HTTP method is used to submit data to a server?", "options": ["GET", "POST", "HEAD", "TRACE"], "answer": 1},
        {"q": "What does DOM stand for?", "options": ["Document Object Model", "Data Object Management", "Direct Output Method", "Document Order Model"], "answer": 0},
        {"q": "Which status code indicates a page was not found?", "options": ["200", "301", "404", "500"], "answer": 2},
        {"q": "Which of these is a client-side JavaScript framework?", "options": ["React", "Django", "Flask", "Laravel"], "answer": 0},
    ],
    "Full Stack Development": [
        {"q": "What does 'full stack' refer to?", "options": ["Only frontend skills", "Only backend skills", "Both frontend and backend skills", "Only database skills"], "answer": 2},
        {"q": "Which of these is a backend framework?", "options": ["React", "Angular", "Express.js", "Bootstrap"], "answer": 2},
        {"q": "What does an API allow applications to do?", "options": ["Style pages", "Communicate and exchange data", "Compile code", "Store passwords"], "answer": 1},
        {"q": "Which stack refers to MongoDB, Express, React, Node?", "options": ["LAMP", "MEAN", "MERN", "WAMP"], "answer": 2},
        {"q": "What is the role of a database in a full stack app?", "options": ["Render UI", "Persist and manage data", "Style components", "Handle DNS"], "answer": 1},
        {"q": "Which protocol is commonly used for real-time communication?", "options": ["WebSocket", "FTP", "SMTP", "IMAP"], "answer": 0},
        {"q": "What is the purpose of middleware in a backend framework?", "options": ["Style HTML", "Process requests between client and server logic", "Compile CSS", "Manage DNS records"], "answer": 1},
        {"q": "Which of these best describes REST APIs?", "options": ["A database engine", "An architectural style for web services", "A CSS framework", "A version control system"], "answer": 1},
        {"q": "What is used to manage environment-specific configuration (like API keys)?", "options": ["CSS variables", "Environment variables", "HTML meta tags", "Cookies only"], "answer": 1},
        {"q": "Which of these is a common ORM used with backend frameworks?", "options": ["SQLAlchemy", "Photoshop", "Figma", "Webpack"], "answer": 0},
    ],
    "Git and GitHub": [
        {"q": "What is Git primarily used for?", "options": ["Version control", "Image editing", "Web hosting", "Database management"], "answer": 0},
        {"q": "Which command initializes a new Git repository?", "options": ["git start", "git init", "git new", "git create"], "answer": 1},
        {"q": "Which command uploads local commits to a remote repository?", "options": ["git pull", "git push", "git fetch", "git clone"], "answer": 1},
        {"q": "What does 'git clone' do?", "options": ["Deletes a repository", "Creates a copy of a remote repository locally", "Merges two branches", "Reverts a commit"], "answer": 1},
        {"q": "What is a 'branch' in Git used for?", "options": ["Storing passwords", "Working on features independently from main code", "Compiling code", "Hosting a website"], "answer": 1},
        {"q": "Which command merges changes from one branch into another?", "options": ["git merge", "git branch", "git status", "git log"], "answer": 0},
        {"q": "What is a 'pull request' on GitHub?", "options": ["A request to delete a repo", "A proposal to merge code changes", "A backup command", "A password reset request"], "answer": 1},
        {"q": "Which command shows the status of changes in a repository?", "options": ["git status", "git show", "git info", "git check"], "answer": 0},
        {"q": "Which file lists items Git should ignore?", "options": [".gitconfig", ".gitignore", ".gitattributes", ".gitlog"], "answer": 1},
        {"q": "What does 'git commit' do?", "options": ["Uploads code to GitHub directly", "Saves a snapshot of staged changes", "Deletes a branch", "Downloads a repository"], "answer": 1},
    ],
    "AI Tools": [
        {"q": "What does LLM stand for in AI?", "options": ["Large Language Model", "Linear Learning Method", "Logical Language Machine", "Local Learning Model"], "answer": 0},
        {"q": "Which of these is a popular AI chatbot tool?", "options": ["Photoshop", "ChatGPT", "AutoCAD", "Excel"], "answer": 1},
        {"q": "What is 'prompt engineering'?", "options": ["Designing hardware circuits", "Crafting effective inputs to guide AI outputs", "Building databases", "Testing network speed"], "answer": 1},
        {"q": "Which technique is used to reduce AI model size for deployment?", "options": ["Model quantization", "Data encryption", "Load balancing", "Firewalling"], "answer": 0},
        {"q": "What is 'fine-tuning' in AI?", "options": ["Adjusting hardware settings", "Further training a model on specific data", "Formatting a hard drive", "Compressing images"], "answer": 1},
        {"q": "Which of these is used for AI image generation?", "options": ["Midjourney", "MySQL", "Jenkins", "Kubernetes"], "answer": 0},
        {"q": "What does 'RAG' commonly stand for in AI tools?", "options": ["Random Access Graph", "Retrieval-Augmented Generation", "Rapid Application Gateway", "Real-time Analytics Group"], "answer": 1},
        {"q": "Which platform provides pretrained models and tools for NLP tasks?", "options": ["Hugging Face", "Adobe Illustrator", "Salesforce", "AutoCAD"], "answer": 0},
        {"q": "What is a common risk of AI models called 'hallucination'?", "options": ["The model crashes the OS", "The model generates plausible but incorrect information", "The model deletes data", "The model runs slower"], "answer": 1},
        {"q": "Which AI tool category helps generate code from natural language?", "options": ["AI coding assistants", "Spreadsheet tools", "Antivirus tools", "Firewall tools"], "answer": 0},
    ],
    "Cloud Computing": [
        {"q": "What does IaaS stand for?", "options": ["Infrastructure as a Service", "Internet as a Service", "Integration as a Service", "Interface as a Service"], "answer": 0},
        {"q": "Which of these is a major cloud service provider?", "options": ["Amazon Web Services", "Adobe Photoshop", "Microsoft Word", "AutoCAD"], "answer": 0},
        {"q": "What does SaaS mean?", "options": ["Software as a Service", "System as a Service", "Storage as a Service", "Security as a Service"], "answer": 0},
        {"q": "What is the main benefit of cloud elasticity?", "options": ["Fixed resource allocation", "Scaling resources up or down based on demand", "Permanent storage only", "Manual server installation"], "answer": 1},
        {"q": "Which model gives users a platform to build and deploy apps without managing servers?", "options": ["PaaS", "On-premise", "Bare metal", "LAN hosting"], "answer": 0},
        {"q": "What is a 'virtual machine' in cloud computing?", "options": ["A physical server", "A software-based emulation of a computer", "A type of database", "A network cable"], "answer": 1},
        {"q": "Which term describes storing data across multiple physical locations for safety?", "options": ["Redundancy/replication", "Fragmentation", "Compression", "Caching only"], "answer": 0},
        {"q": "What is a container (e.g., Docker) primarily used for?", "options": ["Packaging applications with dependencies for consistent deployment", "Editing images", "Managing spreadsheets", "Sending emails"], "answer": 0},
        {"q": "What does 'serverless computing' mean?", "options": ["No servers exist anywhere", "Developers don't manage server infrastructure directly", "Only used for storage", "It requires physical servers on-site"], "answer": 1},
        {"q": "Which cloud deployment model is shared only within one organization?", "options": ["Public cloud", "Private cloud", "Open cloud", "Free cloud"], "answer": 1},
    ],
    "Data Analyst": [
        {"q": "Which tool is widely used for data visualization dashboards?", "options": ["Power BI", "Notepad", "WinRAR", "VLC"], "answer": 0},
        {"q": "Which Python library is commonly used for data manipulation?", "options": ["pandas", "tkinter", "pygame", "flask"], "answer": 0},
        {"q": "What does ETL stand for in data analytics?", "options": ["Extract, Transform, Load", "Evaluate, Test, Launch", "Export, Track, Log", "Encrypt, Transfer, List"], "answer": 0},
        {"q": "Which chart type is best for showing trends over time?", "options": ["Pie chart", "Line chart", "Scatter plot", "Heatmap only"], "answer": 1},
        {"q": "What is a 'null value' in a dataset?", "options": ["A duplicate row", "A missing or undefined value", "The largest value", "A negative number"], "answer": 1},
        {"q": "Which SQL clause is used to filter rows?", "options": ["SELECT", "WHERE", "ORDER BY", "GROUP BY"], "answer": 1},
        {"q": "What does 'data normalization' help achieve?", "options": ["Reducing redundancy and improving consistency", "Increasing duplicate data", "Deleting all records", "Encrypting passwords"], "answer": 0},
        {"q": "Which measure represents the middle value of a sorted dataset?", "options": ["Mean", "Median", "Mode", "Range"], "answer": 1},
        {"q": "What is a KPI in data analytics?", "options": ["Key Performance Indicator", "Known Program Instruction", "Kernel Process Index", "Key Password Input"], "answer": 0},
        {"q": "Which tool is used to write and run SQL queries interactively?", "options": ["A database client/IDE (e.g. MySQL Workbench)", "Photoshop", "Illustrator", "Premiere Pro"], "answer": 0},
    ],
    "IoT": [
        {"q": "What does IoT stand for?", "options": ["Internet of Things", "Internet of Technology", "Integration of Tasks", "Interface of Terminals"], "answer": 0},
        {"q": "Which component in IoT devices collects real-world data?", "options": ["Sensor", "Compiler", "Firewall", "Router only"], "answer": 0},
        {"q": "Which communication protocol is lightweight and commonly used in IoT?", "options": ["MQTT", "FTP", "SMTP", "IMAP"], "answer": 0},
        {"q": "Which microcontroller/board is popular for IoT prototyping?", "options": ["Arduino", "Photoshop", "Excel", "AutoCAD"], "answer": 0},
        {"q": "What is an 'actuator' in an IoT system?", "options": ["A device that senses temperature only", "A component that performs a physical action based on input", "A cloud storage unit", "A programming language"], "answer": 1},
        {"q": "Which network range is typically used for short-range IoT communication?", "options": ["Bluetooth/Zigbee", "Satellite only", "Fiber backbone", "Landline telephone"], "answer": 0},
        {"q": "What is 'edge computing' in the context of IoT?", "options": ["Processing data near the data source instead of a central server", "Editing photos on a device", "A type of firewall", "A cloud billing model"], "answer": 0},
        {"q": "Which of these is a common security concern in IoT devices?", "options": ["Weak default passwords", "Too much RAM", "Excessive screen brightness", "Slow typing speed"], "answer": 0},
        {"q": "What role does the cloud typically play in IoT systems?", "options": ["Storing and processing data collected from devices", "Physically powering the sensors", "Replacing all sensors", "Printing documents"], "answer": 0},
        {"q": "Which industry commonly uses IoT for smart monitoring?", "options": ["Agriculture (smart farming)", "None, IoT is web-only", "Only gaming", "Only word processing"], "answer": 0},
    ],
}
